from rq import get_current_job

from database import SessionLocal
from models import Document, Topic, Flashcard, Question, TopicMastery
from services import document_processing

##

def add_topic_content(topic, content):
    topic.lesson = content["lesson"]

    for flashcard_data in content["flashcards"]:
        topic.flashcards.append(
            Flashcard(
                front=flashcard_data["front"],
                back=flashcard_data["back"]
            )
        )


    for question_data in content["question_bank"]:
        topic.questions.append(
            Question(
                question=question_data["question"],
                options=question_data["options"],
                answer=question_data["answer"],
                difficulty=question_data["difficulty"]
            )
        )


def process_document(document_id: int):
    db = SessionLocal()

    try:
        document = db.get(
            Document,
            document_id
        )

        if (document is None):
            return


        # Commit immediately so the frontend can see that processing has actually started.
        document.status = "processing"
        document.title = "Processing..."
        db.commit()

        if (document.source == "prompt"):
            ai_response = document_processing.generate_outline_from_prompt(document.text)

        else:
            ai_response = document_processing.generate_outline(document.text)


        # Only the outline is generated here. Each topic's content is generated by process_topic when the user asks.
        for i, topic_data in enumerate(ai_response["topics"]):
            topic = Topic(
                name=topic_data["name"],
                order_index=i,
                material=topic_data["material"]
            )


            # Create the user's mastery record for this topic.
            # Only the first topic starts unlocked.
            mastery = TopicMastery(
                user_id=document.user_id,
                status="unlocked" if i == 0 else "locked"
            )

            topic.mastery_records.append(mastery)
            document.topics.append(topic)


        title = ai_response["title"]

        if (title == "Rejected"):
            document.status = "failed"
            document.title = title

        else:
            document.status = "ready"
            document.title = ai_response["title"]


        # Commit all generated study material together. 
        # If construction fails before this commit, no partially generated material is saved.
        # Status will also become "pending" so that processing can try again.
        db.commit()

    except Exception:
        db.rollback()

        document = db.get(
            Document,
            document_id
        )

        job = get_current_job()

        if (document is not None):
            # RQ only retries a job that has retries left, so after the last one the document is failed instead of pending forever.
            if (job is not None and job.should_retry):
                document.status = "pending"
                document.title = "Pending..."

            else:
                document.status = "failed"
                document.title = "Failed"


            db.commit()


        raise


    finally:
        db.close()


def process_topic(topic_id: int):
    db = SessionLocal()

    try:
        topic = db.get(
            Topic,
            topic_id
        )

        if (topic is None):
            return


        topic.content_status = "processing"
        db.commit()

        lines = []

        for other in topic.document.topics:
            line_number = other.order_index + 1
            line = f"{line_number}. {other.name}"
            lines.append(line)


        outline = "\n".join(lines)
        content = document_processing.generate_topic(topic.material, topic.name, outline, topic.document.source)
        add_topic_content(topic, content)

        topic.content_status = "ready"
        db.commit()

    except Exception:
        db.rollback()

        topic = db.get(
            Topic,
            topic_id
        )


        # Not retried automatically, so the user can press generate again instead of waiting on a stuck topic.
        if (topic is not None):
            topic.content_status = "failed"
            db.commit()


        raise


    finally:
        db.close()

