"""add Document source

Revision ID: 556b4d0ee3d8
Revises: cb10b5756981
Create Date: 2026-10-05 19:58:01.740943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556b4d0ee3d8'
down_revision: Union[str, Sequence[str], None] = 'cb10b5756981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(length=20), server_default='file', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
