"""empty message

Revision ID: cb10b5756981
Revises: 0923a734ebb8
Create Date: 2026-10-03 01:23:45.875646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb10b5756981'
down_revision: Union[str, Sequence[str], None] = '0923a734ebb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('content_status', sa.String(length=20), server_default='ready', nullable=False))
    op.add_column('topics', sa.Column('material', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('topics', 'material')
    op.drop_column('topics', 'content_status')
    # ### end Alembic commands ###
